version: '3.8'

services:
  employee-api:
    build:
      context: ./EmployeeManagement.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongo-db:27017
      - MongoDbSettings__DatabaseName=EmployeeDb
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: